services:
  - type: web
    name: anondo-downloader-web
    env: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: gunicorn App:app
